# Site settings
title:       'Chanh의 블로그'
email:       'techchanh@gmail.com'
description: '자기개발자 찮의 블로그'
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://seochanh.github.io' # The base hostname & protocol for your site
twitter:     'https://twitter.com/chchchanhee'
github:      'https://github.com/seochanh'
instagram:   'https://www.instagram.com/chchchanh/'
facebook:    ''
logo: '/images/posts/jekyll.jpg'

markdown:  kramdown
permalink: pretty
paginate:  10

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-sitemap

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - category

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Add collections
collections:
  notes:
    output: true
  poetry:
    output: false

# Pages path
defaults:
  - scope:
      path:   ''
    values:
      layout: 'default'
  - scope:
      path:   ''
    values:
      layout: 'post'
      sitemap: true
  - scope:
      path:   ''
    values:
      layout: 'category'
  - scope:
      path:   ''
      type:   'poetry'
    values:
      layout: 'poem'
  - scope:
      path:   ''
      type:   'notes'
    values:
      layout: 'note'
      sitemap: true
