# Site settings
title:       'Chanh의 블로그'
email:       'techchanh@gmail.com'
description: '코딩하는 취준생 찮의 블로그'
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://seochanh.github.io' # The base hostname & protocol for your site
twitter:     'https://twitter.com/chchchanhee'
github:      'https://github.com/seochanh'
instagram:   'https://www.instagram.com/chchchanh/'
facebook:    ''
logo: '/images/posts/jekyll.jpg'

markdown:  kramdown
permalink: pretty
paginate:  10

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext